openapi: 3.0.2
info:
    title: Computers-API
    version: 1.0.0
    description: >-
        ### This is a Swagger UI for our Games API  


        ### Error handling

        Errors are presented using the HTTP status codes 400-599. The response include a more detailed
        explanation about the error in the body.


        ```

        {
          "error": "Cleartext explanation of the error that occurred"
        }

        ```


        ### Generic API errors

        These error responses can be returned by any of the described endpoints.


        | HTTP status  |  Description |

        |---|---|

        | 400| Bad input parameters or invalid request. More information can be found in the response body.

        | 401| The consumer does not have access to the requested resource or the provided token is not valid.

        | 404| The requested resource can not be found or the user does not have access to the resource.

        | 5XX| A server error has occurred while processing the request.
paths:
    '/orders{ID}':
        get:
            tags:
                - orders
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Get a list of all orders:
                                    value: |-
                                        [
                                            {orderID:1, ProductID:8, ]}
                                            {orderID:4, ProductID:9]}
                                        ]
                    description: Returns order information
                '404':
                    description: Order not found
            summary: Get a list of all ORDERS
            description: |+
                RETURNS a list of all ORDERS

        post:
            responses:
                '200':
                    description: Order created
                '400':
                    description: Error creating order
            summary: Create an order
        delete:
            responses:
                '200':
                    description: Order deleted.
                '400':
                    description: Error deleting order
                '401':
                    description: Unauthorized to delete order
            summary: Delete an order
        parameters:
            -
                name: ID
                in: path
                required: true
    '/products{ID}':
        description: ''
        get:
            tags:
                - products
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Single product:
                                    value: |-
                                        [
                                            {id:1,name:"Gaming PC Ultra", price: 3999}
                                        ]
                    description: Returns a list and information of requested products
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value:
                                        Error: Product not found
                    description: Product not found.
            summary: Get a list of all PRODUCTS
            description: |
                Identifier of product
        post:
            responses:
                '200':
                    description: Product has been created
                '400':
                    description: Error creating product
                '401':
                    description: Not authorized to create a new product
            summary: Create product
        delete:
            responses:
                '200':
                    description: Product has been deleted
                '400':
                    description: Error deleting product
                '401':
                    description: Unauthorized to delete product
            summary: Delete product
        parameters:
            -
                name: ID
                in: path
                required: true
    '/user{ID}':
        get:
            tags:
                - users
            responses:
                '200':
                    description: Returns user information
                '400':
                    description: Error getting user inforation
            summary: Get info about an user
            description: Returns information about an user
        post:
            responses:
                '200':
                    description: User has been created
                '400':
                    description: Error creating user
            summary: Create user
        delete:
            responses:
                '200':
                    description: User has been deleted
                '400':
                    description: Error deleting user.
                '401':
                    description: Not authorized to delete user.
            summary: Delete user
        parameters:
            -
                name: ID
                in: path
                required: true
    '/invoices{ID}':
        get:
            tags:
                - invoices
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Get a list of all invoices:
                                    value: |-
                                        [
                                            [
                                            {orderID:1, clientID:2, invoiceID: 3,description:["Intel® Core™ i5-13600KF","GIGABYTE B760 GAMING","GeForce RTX™ 4060 8GB","16GB DDR5","1000 GB HDD"]},
                                            {orderID:4, clientID:5, invoiceID: 6,description:["Intel Core i5-12400F","GIGABYTE H610","GeForce RTX™ 4060 8GB","16GB DDR5","1000 GB HDD"]}
                                        ]
                                        ]
                    description: Returns the information of an invoice
                '404':
                    description: Invoice not found
            summary: Get a list of all INVOICES
            description: RETURNS a list of all INVOICES
        post:
            responses:
                '200':
                    description: Invoice has been created
                '400':
                    description: Error creating invoice
            summary: Create an invoice
        delete:
            responses:
                '200':
                    description: Invoice has been deleted
                '400':
                    description: Error deleting invoice
                '401':
                    description: Not authorized to delete invoice
            summary: Delete an invoice
        parameters:
            -
                name: ID
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for errir
            description: ''
            type: object
            properties:
                Error:
                    type: string
            example:
                Error: Error message
        product:
            title: Root Type for product
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                price:
                    format: int32
                    type: integer
            example:
                id: 1
                name: Gaming PC Ultra
                price: 3999
        user:
            title: Root Type for user
            description: ''
            type: array
            items:
                type: string
            example:
                - Marcus Toman
                - Rasmus Jalakas
        delete:
            title: Root Type for delete-product
            description: ''
            required:
                - id
            type: object
            properties:
                id:
                    type: string
            example:
                id: 1
tags:
    -
        name: products
        description: ''
